
import sdl2mixer,\
	Mix_Init,'Mix_Init',\
	Mix_Quit,'Mix_Quit',\
	Mix_LoadWAV_RW,'Mix_LoadWAV_RW',\
	Mix_LoadMUS,'Mix_LoadMUS',\
	Mix_PlayChannelTimed,'Mix_PlayChannelTimed',\
	Mix_HaltChannel,'Mix_HaltChannel',\
	Mix_PlayMusic,'Mix_PlayMusic',\
	Mix_HaltMusic,'Mix_HaltMusic',\
	Mix_FreeChunk,'Mix_FreeChunk',\
	Mix_FreeMusic,'Mix_FreeMusic',\
	Mix_OpenAudio,'Mix_OpenAudio',\
	Mix_CloseAudio,'Mix_CloseAudio'

