
import sdl2net,\
	SDLNet_ResolveHost,''\
	SDLNet_ResolveIP,''\
	SDLNet_SocketReady,''\
	SDLNet_TCP_Open,''\
	SDLNet_TCP_Accept,''\
	SDLNet_TCP_GetPeerAddress,''\
	SDLNet_TCP_Send,''\
	SDLNet_TCP_Recv,''\
	SDLNet_TCP_Close,''\
	SDLNet_AllocPacket,''\
	SDLNet_FreePacket,''\
	SDLNet_UDP_Open,''\
	SDLNet_UDP_Bind,''\
	SDLNet_UDP_Unbind,''\
	SDLNet_UDP_GetPeerAddress,''\
	SDLNet_UDP_Send,''\
	SDLNet_UDP_Recv,''\
	SDLNet_UDP_Close,''\
	SDLNet_AllocSocketSet,''\
	SDLNet_TCP_AddSocket,''\
	SDLNet_UDP_AddSocket,''\
	SDLNet_TCP_DelSocket,''\
	SDLNet_UDP_DelSocket,''\
	SDLNet_CheckSockets,''\
	SDLNet_FreeSocketSet,''